### ISSUE TITLE
Bind to a version of webkit that supports KeyboardEvent.key

### ISSUE THREAD

**Issue by Mikolaj** [gtk2hs/webkit#20]
KeyboardEvent.key, the new standard that all browsers, except Safari already support, has just been added to webkit:

https://bugs.webkit.org/show_bug.cgi?id=36267

**Comment by Mikolaj** [comment]
And now a version of WebKitGTK+ with support for key and code properties on keyboard events has been released: https://webkitgtk.org/2017/01/20/webkitgtk2.15.3-released.html

**Comment by hamishmack** [comment]
These bindings are for WebKit1 only.  The last version of WebKitGTK to include WebKit1 was 2.4.

You might be able to get this to work with WebKit2 using the `gi-webkit2` package however keep in mind that with WebKit2 the DOM is not in the Gtk application process (so unless you write a Web Extension you may not be able to access this function).

We should add support for this to `ghcjs-dom`.  Since it can be used with `jsaddle-webkit2gtk` to get around the DOM process issue.

**Comment by Mikolaj** [comment]
Yes, actually I need to this for ghcjs-dom, the ghcjs-dom-webkit flavour, to use directly with ghcjs. Should I instead open an issue there?

**Comment by hamishmack** [comment]
I you could open it on `ghcjs-dom`, that would be great. Thanks.

**Comment by Mikolaj** [comment]
Done: https://github.com/ghcjs/ghcjs-dom/issues/62 
Thank you. Closing.
